# Generated by Django 5.0.2 on 2024-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewSovet', '0005_rename_title_kz_viewsovet_title_kk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewsovet',
            options={'verbose_name_plural': 'Публикации'},
        ),
    ]
