# Generated by Django 5.0.2 on 2024-05-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewSovet', '0008_alter_viewsovet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewsovet',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
