# Generated by Django 5.0.2 on 2024-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewSovet', '0009_alter_viewsovet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewsovet',
            name='title_en',
            field=models.CharField(null=True, verbose_name='Название'),
        ),
    ]
