# Generated by Django 5.0.2 on 2024-05-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgStruct', '0002_alter_orgstruct_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgstruct',
            options={'verbose_name': 'Схема', 'verbose_name_plural': 'Схемы отделов'},
        ),
    ]
