# Generated by Django 5.0.2 on 2024-10-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgStruct', '0004_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='info_en',
            field=models.TextField(null=True, verbose_name='Информация об отделе'),
        ),
        migrations.AddField(
            model_name='departments',
            name='info_kk',
            field=models.TextField(null=True, verbose_name='Информация об отделе'),
        ),
        migrations.AddField(
            model_name='departments',
            name='info_ru',
            field=models.TextField(null=True, verbose_name='Информация об отделе'),
        ),
        migrations.AddField(
            model_name='departments',
            name='name_en',
            field=models.CharField(null=True, verbose_name='Название отдела'),
        ),
        migrations.AddField(
            model_name='departments',
            name='name_kk',
            field=models.CharField(null=True, verbose_name='Название отдела'),
        ),
        migrations.AddField(
            model_name='departments',
            name='name_ru',
            field=models.CharField(null=True, verbose_name='Название отдела'),
        ),
    ]
