# Generated by Django 5.0.2 on 2024-05-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_people_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={},
        ),
    ]
