# Generated by Django 5.0.2 on 2024-06-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_alter_people_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Основной текст')),
            ],
            options={
                'verbose_name': 'Информация о врачах',
                'verbose_name_plural': 'Информация о врачах',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Основной текст')),
            ],
            options={
                'verbose_name': 'Информация о педагогах',
                'verbose_name_plural': 'Информация о педагогах',
            },
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Персонал'},
        ),
    ]
