# Generated by Django 5.0.2 on 2024-06-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_doctors_teachers_alter_people_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='content_kk',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='title_kk',
            field=models.CharField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='content_kk',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='title_kk',
            field=models.CharField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Заголовок'),
        ),
    ]
