# Generated by Django 5.0.2 on 2024-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_doctors_content_kk_doctors_content_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='title_en',
            field=models.CharField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='people',
            name='post_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='title_en',
            field=models.CharField(null=True, verbose_name='Заголовок'),
        ),
    ]
