# Generated by Django 5.0.2 on 2024-06-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_doctors_content_en_doctors_title_en_people_post_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='content_kk',
            new_name='content_kz',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='title_kk',
            new_name='title_kz',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='post_kk',
            new_name='post_kz',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='content_kk',
            new_name='content_kz',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='title_kk',
            new_name='title_kz',
        ),
    ]
