# Generated by Django 5.0.2 on 2024-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_rename_additionally_kz_competitioninfo_additionally_kk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitioninfo',
            options={'verbose_name_plural': 'Информация о куонкурсе'},
        ),
        migrations.AlterModelOptions(
            name='vacancies',
            options={'verbose_name_plural': 'Вакансии'},
        ),
    ]
