# Generated by Django 5.0.2 on 2024-05-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_competitioninfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitioninfo',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информация о конкурсе'},
        ),
        migrations.AlterModelOptions(
            name='vacancies',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
