# Generated by Django 5.0.2 on 2024-05-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_alter_competitioninfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitioninfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vacancies',
            options={},
        ),
    ]
