# Generated by Django 5.0.2 on 2024-06-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_alter_competitioninfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='requirement',
            field=models.TextField(blank=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='requirement_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='requirement_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Требования'),
        ),
    ]
