# Generated by Django 5.0.2 on 2024-06-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_alter_vacancies_requirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitioninfo',
            name='additionally',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='additionally_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='additionally_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='addmisions',
            field=models.TextField(blank=True, verbose_name='Условия допуска к участию'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='addmisions_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Условия допуска к участию'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='addmisions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Условия допуска к участию'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='documents',
            field=models.TextField(blank=True, verbose_name='Список предоставляемсях документов'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='documents_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Список предоставляемсях документов'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='documents_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Список предоставляемсях документов'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='enterpriseAddress',
            field=models.TextField(blank=True, verbose_name='Адрес предприятия'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='enterpriseAddress_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес предприятия'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='enterpriseAddress_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес предприятия'),
        ),
    ]
