# Generated by Django 5.0.2 on 2024-06-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_alter_competitioninfo_additionally_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitioninfo',
            name='additionally',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='addmisions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия допуска к участию'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='documents',
            field=models.TextField(blank=True, null=True, verbose_name='Список предоставляемсях документов'),
        ),
        migrations.AlterField(
            model_name='competitioninfo',
            name='enterpriseAddress',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес предприятия'),
        ),
    ]
