# Generated by Django 5.0.2 on 2024-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_alter_competitioninfo_additionally_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitioninfo',
            name='additionally_en',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='addmisions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Условия допуска к участию'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='compAddress_en',
            field=models.TextField(null=True, verbose_name='Адрес конкурса'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='documents_en',
            field=models.TextField(blank=True, null=True, verbose_name='Список предоставляемсях документов'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='enterpriseAddress_en',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес предприятия'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='requirement_en',
            field=models.TextField(blank=True, null=True, verbose_name='Требования'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='vacancy_en',
            field=models.TextField(null=True, verbose_name='Вакансия'),
        ),
    ]
