# Generated by Django 5.0.2 on 2024-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiCorruptions', '0004_rename_title_kz_anticorruption_title_kk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anticorruption',
            options={'verbose_name_plural': 'Противодействие коррупции'},
        ),
    ]
