# Generated by Django 5.0.2 on 2024-06-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laborProtection', '0003_rename_content_kk_laborprotection_content_kz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laborprotection',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='laborprotection',
            old_name='title_kz',
            new_name='title_kk',
        ),
    ]
