# Generated by Django 5.0.2 on 2024-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='booking',
            name='title_en',
            field=models.CharField(null=True, verbose_name='Заголовок'),
        ),
    ]
