# Generated by Django 5.0.2 on 2024-06-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_content_en_booking_title_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='content_kk',
            new_name='content_kz',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='title_kk',
            new_name='title_kz',
        ),
    ]
