# Generated by Django 5.0.2 on 2024-05-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название презентации')),
                ('name_ru', models.CharField(null=True, verbose_name='Название презентации')),
                ('name_kk', models.CharField(null=True, verbose_name='Название презентации')),
                ('info', models.FileField(upload_to='science', verbose_name='Презентация')),
            ],
            options={
                'verbose_name': 'Презентация',
                'verbose_name_plural': 'Презентации',
            },
        ),
    ]
