# Generated by Django 5.0.2 on 2024-06-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienceBlock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_ru', models.TextField(null=True)),
                ('content_kk', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Подпунты к основным пунктам Науке и Достижениям',
            },
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Основыне пункты достижений')),
                ('title_ru', models.CharField(null=True, verbose_name='Основыне пункты достижений')),
                ('title_kk', models.CharField(null=True, verbose_name='Основыне пункты достижений')),
                ('addInfo', models.ManyToManyField(blank=True, null=True, related_name='science_addinfo', to='scienceBlock.addinfo', verbose_name='Подпункты')),
                ('addInfo_kk', models.ManyToManyField(blank=True, null=True, related_name='science_addinfo', to='scienceBlock.addinfo', verbose_name='Подпункты')),
                ('addInfo_ru', models.ManyToManyField(blank=True, null=True, related_name='science_addinfo', to='scienceBlock.addinfo', verbose_name='Подпункты')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Наука и Достижения',
            },
        ),
    ]
