# Generated by Django 5.0.2 on 2024-06-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienceBlock', '0002_addinfo_science'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='science',
            name='addInfo_kk',
        ),
        migrations.RemoveField(
            model_name='science',
            name='addInfo_ru',
        ),
        migrations.RemoveField(
            model_name='science',
            name='addInfo',
        ),
        migrations.AddField(
            model_name='science',
            name='addInfo_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Подпункты'),
        ),
        migrations.AddField(
            model_name='science',
            name='addInfo_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Подпункты'),
        ),
        migrations.DeleteModel(
            name='AddInfo',
        ),
        migrations.AddField(
            model_name='science',
            name='addInfo',
            field=models.TextField(blank=True, verbose_name='Подпункты'),
        ),
    ]
