# Generated by Django 5.0.2 on 2024-06-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienceBlock', '0004_alter_science_title_alter_science_title_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='science',
            name='addInfoTitle',
            field=models.CharField(blank=True, verbose_name='Заголовок подпунктов'),
        ),
        migrations.AddField(
            model_name='science',
            name='addInfoTitle_kk',
            field=models.CharField(blank=True, null=True, verbose_name='Заголовок подпунктов'),
        ),
        migrations.AddField(
            model_name='science',
            name='addInfoTitle_ru',
            field=models.CharField(blank=True, null=True, verbose_name='Заголовок подпунктов'),
        ),
    ]
