# Generated by Django 5.0.2 on 2024-06-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienceBlock', '0005_science_addinfotitle_science_addinfotitle_kk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceSovet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Основыне пункты достижений')),
                ('title_ru', models.TextField(null=True, verbose_name='Основыне пункты достижений')),
                ('title_kk', models.TextField(null=True, verbose_name='Основыне пункты достижений')),
                ('addInfo', models.TextField(blank=True, verbose_name='Подпункты')),
                ('addInfo_ru', models.TextField(blank=True, null=True, verbose_name='Подпункты')),
                ('addInfo_kk', models.TextField(blank=True, null=True, verbose_name='Подпункты')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Научно-Технический Совет',
            },
        ),
    ]
