# Generated by Django 5.0.2 on 2024-06-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienceBlock', '0006_sciencesovet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sciencesovet',
            name='addInfo',
        ),
        migrations.RemoveField(
            model_name='sciencesovet',
            name='addInfo_kk',
        ),
        migrations.RemoveField(
            model_name='sciencesovet',
            name='addInfo_ru',
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='content',
            field=models.TextField(blank=True, verbose_name='Основная информация'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='content_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Основная информация'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Основная информация'),
        ),
        migrations.AlterField(
            model_name='sciencesovet',
            name='title',
            field=models.TextField(verbose_name='Заголовок Совета'),
        ),
        migrations.AlterField(
            model_name='sciencesovet',
            name='title_kk',
            field=models.TextField(null=True, verbose_name='Заголовок Совета'),
        ),
        migrations.AlterField(
            model_name='sciencesovet',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='Заголовок Совета'),
        ),
    ]
