# Generated by Django 5.0.2 on 2024-06-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scienceBlock', '0008_scienceplans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScienceInfo',
            new_name='ScienceAchievments',
        ),
    ]
