# Generated by Django 5.0.2 on 2024-06-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scienceBlock', '0009_rename_scienceinfo_scienceachievments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='science',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Наукачные разработки'},
        ),
        migrations.AlterModelOptions(
            name='scienceachievments',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
    ]
