# Generated by Django 5.0.2 on 2024-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienceBlock', '0010_alter_science_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='science',
            name='addInfoTitle_en',
            field=models.CharField(blank=True, null=True, verbose_name='Заголовок подпунктов'),
        ),
        migrations.AddField(
            model_name='science',
            name='addInfo_en',
            field=models.TextField(blank=True, null=True, verbose_name='Подпункты'),
        ),
        migrations.AddField(
            model_name='science',
            name='title_en',
            field=models.TextField(null=True, verbose_name='Основыне пункты достижений'),
        ),
        migrations.AddField(
            model_name='scienceachievments',
            name='name_en',
            field=models.CharField(null=True, verbose_name='Название презентации'),
        ),
        migrations.AddField(
            model_name='scienceplans',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Основная информация'),
        ),
        migrations.AddField(
            model_name='scienceplans',
            name='title_en',
            field=models.TextField(null=True, verbose_name='Заголовок Совета'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Основная информация'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='title_en',
            field=models.TextField(null=True, verbose_name='Заголовок Совета'),
        ),
    ]
