# Generated by Django 5.0.2 on 2024-06-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scienceBlock', '0012_rename_addinfotitle_kk_science_addinfotitle_kz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='science',
            old_name='addInfoTitle_kz',
            new_name='addInfoTitle_kk',
        ),
        migrations.RenameField(
            model_name='science',
            old_name='addInfo_kz',
            new_name='addInfo_kk',
        ),
        migrations.RenameField(
            model_name='science',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='scienceachievments',
            old_name='name_kz',
            new_name='name_kk',
        ),
        migrations.RenameField(
            model_name='scienceplans',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='scienceplans',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='sciencesovet',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='sciencesovet',
            old_name='title_kz',
            new_name='title_kk',
        ),
    ]
