# Generated by Django 5.0.2 on 2024-07-25 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienceBlock', '0013_rename_addinfotitle_kz_science_addinfotitle_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sciencesovet',
            name='content',
        ),
        migrations.RemoveField(
            model_name='sciencesovet',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='sciencesovet',
            name='content_kk',
        ),
        migrations.RemoveField(
            model_name='sciencesovet',
            name='content_ru',
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='creation',
            field=models.FileField(blank=True, upload_to='science', verbose_name='Приказ о создании'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='creation_en',
            field=models.FileField(blank=True, null=True, upload_to='science', verbose_name='Приказ о создании'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='creation_kk',
            field=models.FileField(blank=True, null=True, upload_to='science', verbose_name='Приказ о создании'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='creation_ru',
            field=models.FileField(blank=True, null=True, upload_to='science', verbose_name='Приказ о создании'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='meetings',
            field=models.TextField(blank=True, verbose_name='Заседания'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='meetings_en',
            field=models.TextField(blank=True, null=True, verbose_name='Заседания'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='meetings_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Заседания'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='meetings_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Заседания'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='regulation',
            field=models.FileField(blank=True, upload_to='science', verbose_name='Положение'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='regulation_en',
            field=models.FileField(blank=True, null=True, upload_to='science', verbose_name='Положение'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='regulation_kk',
            field=models.FileField(blank=True, null=True, upload_to='science', verbose_name='Положение'),
        ),
        migrations.AddField(
            model_name='sciencesovet',
            name='regulation_ru',
            field=models.FileField(blank=True, null=True, upload_to='science', verbose_name='Положение'),
        ),
        migrations.AlterField(
            model_name='sciencesovet',
            name='title',
            field=models.CharField(blank=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sciencesovet',
            name='title_en',
            field=models.CharField(blank=True, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sciencesovet',
            name='title_kk',
            field=models.CharField(blank=True, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sciencesovet',
            name='title_ru',
            field=models.CharField(blank=True, null=True, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='ScienceSovetPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название документа')),
                ('title_ru', models.CharField(null=True, verbose_name='Название документа')),
                ('title_kk', models.CharField(null=True, verbose_name='Название документа')),
                ('title_en', models.CharField(null=True, verbose_name='Название документа')),
                ('document', models.FileField(blank=True, upload_to='science', verbose_name='Документ')),
                ('document_ru', models.FileField(blank=True, null=True, upload_to='science', verbose_name='Документ')),
                ('document_kk', models.FileField(blank=True, null=True, upload_to='science', verbose_name='Документ')),
                ('document_en', models.FileField(blank=True, null=True, upload_to='science', verbose_name='Документ')),
                ('sovet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scienceBlock.sciencesovet', verbose_name='Научно-технический совет')),
                ('sovet_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scienceBlock.sciencesovet', verbose_name='Научно-технический совет')),
                ('sovet_kk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scienceBlock.sciencesovet', verbose_name='Научно-технический совет')),
                ('sovet_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scienceBlock.sciencesovet', verbose_name='Научно-технический совет')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы Научно-Технического Совета',
            },
        ),
    ]
