# Generated by Django 5.0.2 on 2024-05-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(verbose_name='Введение')),
                ('intro_ru', models.TextField(null=True, verbose_name='Введение')),
                ('intro_kk', models.TextField(null=True, verbose_name='Введение')),
                ('partners', models.TextField(verbose_name='Список партнеров')),
                ('partners_ru', models.TextField(null=True, verbose_name='Список партнеров')),
                ('partners_kk', models.TextField(null=True, verbose_name='Список партнеров')),
            ],
        ),
    ]
