# Generated by Django 5.0.2 on 2024-06-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_partners', '0006_partners_intro_en_partners_partners_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='intro_kk',
            new_name='intro_kz',
        ),
        migrations.RenameField(
            model_name='partners',
            old_name='partners_kk',
            new_name='partners_kz',
        ),
    ]
