# Generated by Django 5.0.2 on 2024-06-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_partners', '0007_rename_intro_kk_partners_intro_kz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='intro_kz',
            new_name='intro_kk',
        ),
        migrations.RenameField(
            model_name='partners',
            old_name='partners_kz',
            new_name='partners_kk',
        ),
    ]
