# Generated by Django 5.0.2 on 2024-04-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='accreditation/', verbose_name='Изображение')),
                ('file', models.FileField(upload_to='docs/', verbose_name='Документ')),
            ],
        ),
    ]
