# Generated by Django 5.0.2 on 2024-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0002_accreditation_title_kk_accreditation_title_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accreditation',
            options={'verbose_name_plural': 'Аккредитация'},
        ),
    ]
