# Generated by Django 5.0.2 on 2024-05-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0003_alter_accreditation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accreditation',
            options={'verbose_name': 'Аккредитация', 'verbose_name_plural': 'Аккредитации'},
        ),
    ]
