# Generated by Django 5.0.2 on 2024-05-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0006_alter_accreditation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accreditation',
            name='image',
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='file',
            field=models.FileField(upload_to='accreditation/', verbose_name='Документ'),
        ),
    ]
