# Generated by Django 5.0.2 on 2024-05-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0007_remove_accreditation_image_alter_accreditation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='medicine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accreditation',
            name='science',
            field=models.BooleanField(default=False),
        ),
    ]
