# Generated by Django 5.0.2 on 2024-05-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0008_accreditation_medicine_accreditation_science'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='type',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Тип файла'),
        ),
    ]
