# Generated by Django 5.0.2 on 2024-06-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0010_accreditation_title_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accreditation',
            old_name='title_kk',
            new_name='title_kz',
        ),
    ]
