# Generated by Django 5.0.2 on 2024-06-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0011_rename_title_kk_accreditation_title_kz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accreditation',
            old_name='title_kz',
            new_name='title_kk',
        ),
    ]
