# Generated by Django 5.0.2 on 2024-06-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0012_rename_title_kz_accreditation_title_kk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation',
            name='medicine',
            field=models.BooleanField(default=False, verbose_name='Медицинская аккредитация'),
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='science',
            field=models.BooleanField(default=False, verbose_name='Научная аккредитация'),
        ),
    ]
