# Generated by Django 5.0.2 on 2024-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Title'),
        ),
    ]
