# Generated by Django 5.0.2 on 2024-05-18 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_post_title_alter_post_title_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='file_kk',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='file_ru',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='post_kk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post'),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='post_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post'),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='type_kk',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='type_ru',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
