# Generated by Django 5.0.2 on 2024-05-27 12:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_post_options_alter_postattachment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='postattachment',
            options={'verbose_name': 'Файлы', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_kk',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='file',
            field=models.FileField(upload_to='images/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='file_kk',
            field=models.FileField(null=True, upload_to='images/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='file_ru',
            field=models.FileField(null=True, upload_to='images/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='post_kk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='post_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='type',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='type_kk',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='type_ru',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Тип файла'),
        ),
    ]
