# Generated by Django 5.0.2 on 2024-06-24 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_post_options_alter_postattachment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='file_en',
            field=models.FileField(null=True, upload_to='images/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='post_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='type_en',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Тип файла'),
        ),
    ]
