# Generated by Django 5.0.2 on 2024-06-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_rename_content_kk_post_content_kz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='postattachment',
            old_name='file_kz',
            new_name='file_kk',
        ),
        migrations.RenameField(
            model_name='postattachment',
            old_name='post_kz',
            new_name='post_kk',
        ),
        migrations.RenameField(
            model_name='postattachment',
            old_name='type_kz',
            new_name='type_kk',
        ),
    ]
