# Generated by Django 5.0.2 on 2024-06-24 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_remove_postattachment_file_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPostAttAdmin',
            fields=[
                ('postattachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.postattachment')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
            },
            bases=('news.postattachment',),
        ),
    ]
