# Generated by Django 5.0.2 on 2024-06-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_custompostattadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPostAttAdmin',
        ),
    ]
