# Generated by Django 5.0.2 on 2024-05-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0004_alter_userfeedback_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
    ]
