# Generated by Django 5.0.2 on 2024-04-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ethica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название файла')),
                ('name_ru', models.CharField(null=True, verbose_name='Название файла')),
                ('name_kk', models.CharField(null=True, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='docs/', verbose_name='Файл')),
                ('type', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
