# Generated by Django 5.0.2 on 2024-05-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethica', '0004_alter_ethica_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ethica',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы об этике'},
        ),
    ]
