# Generated by Django 5.0.2 on 2024-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethica', '0005_alter_ethica_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethica',
            name='name_en',
            field=models.CharField(null=True, verbose_name='Название файла'),
        ),
    ]
