# Generated by Django 5.0.2 on 2024-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPage', '0005_alter_aboutinfo_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutinfo',
            options={'verbose_name_plural': 'Информация о НИИ'},
        ),
    ]
