# Generated by Django 5.0.2 on 2024-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPage', '0009_alter_aboutinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='About_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='LDO_en',
            field=models.TextField(null=True, verbose_name='Лечебно-Диагностическое отделение'),
        ),
    ]
