# Generated by Django 5.0.2 on 2024-06-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPage', '0010_aboutinfo_about_en_aboutinfo_ldo_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutinfo',
            old_name='About_kk',
            new_name='About_kz',
        ),
        migrations.RenameField(
            model_name='aboutinfo',
            old_name='LDO_kk',
            new_name='LDO_kz',
        ),
    ]
