# Generated by Django 5.0.2 on 2024-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProvActs', '0005_rename_description_kz_provacts_description_kk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provacts',
            options={'verbose_name_plural': 'Акты'},
        ),
    ]
