# Generated by Django 5.0.2 on 2024-05-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProvActs', '0006_alter_provacts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provacts',
            options={'verbose_name': 'Акт', 'verbose_name_plural': 'Акты'},
        ),
    ]
