# Generated by Django 5.0.2 on 2024-05-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProvActs', '0007_alter_provacts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provacts',
            options={},
        ),
    ]
