# Generated by Django 5.0.2 on 2024-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProvActs', '0009_alter_provacts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='provacts',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание правовых актов'),
        ),
    ]
