# Generated by Django 5.0.2 on 2024-04-14 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_rename_title_kz_ads_title_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
