# Generated by Django 5.0.2 on 2024-04-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_files_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='type',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
