# Generated by Django 5.0.2 on 2024-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_files_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name_plural': 'Группа объявлений'},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name_plural': 'файлы и объявления'},
        ),
    ]
