# Generated by Django 5.0.2 on 2024-05-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_alter_ads_options_alter_files_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'файл или объявление', 'verbose_name_plural': 'файлы и объявления'},
        ),
    ]
