# Generated by Django 5.0.2 on 2024-05-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_alter_files_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={},
        ),
    ]
