# Generated by Django 5.0.2 on 2024-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_alter_ads_options_alter_files_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='title_en',
            field=models.CharField(null=True, verbose_name='Заголовок объявления'),
        ),
        migrations.AddField(
            model_name='files',
            name='name_en',
            field=models.CharField(null=True, verbose_name='Название файла'),
        ),
    ]
