# Generated by Django 5.0.2 on 2024-07-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEK', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lek',
            name='file',
        ),
        migrations.AddField(
            model_name='lek',
            name='contacts',
            field=models.TextField(blank=True, verbose_name='Инструкции по обращению'),
        ),
        migrations.AddField(
            model_name='lek',
            name='contacts_en',
            field=models.TextField(blank=True, null=True, verbose_name='Инструкции по обращению'),
        ),
        migrations.AddField(
            model_name='lek',
            name='contacts_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Инструкции по обращению'),
        ),
        migrations.AddField(
            model_name='lek',
            name='contacts_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Инструкции по обращению'),
        ),
        migrations.AddField(
            model_name='lek',
            name='creation',
            field=models.FileField(blank=True, upload_to='science', verbose_name='Приказ о создании'),
        ),
        migrations.AddField(
            model_name='lek',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lek',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lek',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lek',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lek',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Инструкции по обращению'),
        ),
        migrations.AddField(
            model_name='lek',
            name='instructions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Инструкции по обращению'),
        ),
        migrations.AddField(
            model_name='lek',
            name='instructions_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Инструкции по обращению'),
        ),
        migrations.AddField(
            model_name='lek',
            name='instructions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Инструкции по обращению'),
        ),
        migrations.AddField(
            model_name='lek',
            name='meetings',
            field=models.TextField(blank=True, verbose_name='Заседания'),
        ),
        migrations.AddField(
            model_name='lek',
            name='meetings_en',
            field=models.TextField(blank=True, null=True, verbose_name='Заседания'),
        ),
        migrations.AddField(
            model_name='lek',
            name='meetings_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Заседания'),
        ),
        migrations.AddField(
            model_name='lek',
            name='meetings_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Заседания'),
        ),
        migrations.AddField(
            model_name='lek',
            name='regulation',
            field=models.FileField(blank=True, upload_to='science', verbose_name='Положение'),
        ),
        migrations.AddField(
            model_name='lek',
            name='standarts',
            field=models.TextField(blank=True, verbose_name='Инструкции по обращению'),
        ),
        migrations.AddField(
            model_name='lek',
            name='standarts_en',
            field=models.TextField(blank=True, null=True, verbose_name='Инструкции по обращению'),
        ),
        migrations.AddField(
            model_name='lek',
            name='standarts_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Инструкции по обращению'),
        ),
        migrations.AddField(
            model_name='lek',
            name='standarts_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Инструкции по обращению'),
        ),
    ]
