# Generated by Django 5.0.2 on 2024-07-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEK', '0002_remove_lek_file_lek_contacts_lek_contacts_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LEKDocForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название формы документа')),
                ('title_ru', models.CharField(null=True, verbose_name='Название формы документа')),
                ('title_kk', models.CharField(null=True, verbose_name='Название формы документа')),
                ('title_en', models.CharField(null=True, verbose_name='Название формы документа')),
                ('link', models.TextField(verbose_name='Ссылка на форму документа')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы документов',
            },
        ),
        migrations.CreateModel(
            name='LEKPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название документа')),
                ('title_ru', models.CharField(null=True, verbose_name='Название документа')),
                ('title_kk', models.CharField(null=True, verbose_name='Название документа')),
                ('title_en', models.CharField(null=True, verbose_name='Название документа')),
                ('document', models.FileField(blank=True, upload_to='LEK', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы ЛЭК',
            },
        ),
        migrations.AlterField(
            model_name='lek',
            name='creation',
            field=models.FileField(blank=True, upload_to='LEK', verbose_name='Приказ о создании'),
        ),
        migrations.AlterField(
            model_name='lek',
            name='regulation',
            field=models.FileField(blank=True, upload_to='LEK', verbose_name='Положение'),
        ),
    ]
