# Generated by Django 5.0.2 on 2024-07-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEK', '0004_lekmeetings_lekregulation_alter_lek_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lek',
            name='creation_title',
            field=models.CharField(default=12, verbose_name='Название приказа'),
            preserve_default=False,
        ),
    ]
