# Generated by Django 5.0.2 on 2024-07-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEK', '0005_lek_creation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lek',
            name='creation_title_en',
            field=models.CharField(null=True, verbose_name='Название приказа'),
        ),
        migrations.AddField(
            model_name='lek',
            name='creation_title_kk',
            field=models.CharField(null=True, verbose_name='Название приказа'),
        ),
        migrations.AddField(
            model_name='lek',
            name='creation_title_ru',
            field=models.CharField(null=True, verbose_name='Название приказа'),
        ),
    ]
