# Generated by Django 5.0.2 on 2024-04-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategicDevelopment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicdev',
            name='name_kk',
            field=models.CharField(null=True, verbose_name='Название файла'),
        ),
        migrations.AddField(
            model_name='strategicdev',
            name='name_ru',
            field=models.CharField(null=True, verbose_name='Название файла'),
        ),
    ]
