# Generated by Django 5.0.2 on 2024-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategicDevelopment', '0003_strategicdev_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategicdev',
            options={'verbose_name_plural': 'Файлы о развитии'},
        ),
    ]
