# Generated by Django 5.0.2 on 2024-05-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategicDevelopment', '0004_alter_strategicdev_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategicdev',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы о развитии'},
        ),
    ]
