# Generated by Django 5.0.2 on 2024-06-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategicDevelopment', '0008_strategicdev_name_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategicdev',
            old_name='name_kk',
            new_name='name_kz',
        ),
    ]
