# Generated by Django 5.0.2 on 2024-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medServices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medservices',
            options={'verbose_name_plural': 'Файлы'},
        ),
    ]
