# Generated by Django 5.0.2 on 2024-05-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medServices', '0003_alter_medservices_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medservices',
            options={},
        ),
    ]
