# Generated by Django 5.0.2 on 2024-06-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medServices', '0005_alter_medservices_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Заголовок')),
                ('title_ru', models.CharField(null=True, verbose_name='Заголовок')),
                ('title_kk', models.CharField(null=True, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Основной текст')),
                ('content_ru', models.TextField(null=True, verbose_name='Основной текст')),
                ('content_kk', models.TextField(null=True, verbose_name='Основной текст')),
            ],
            options={
                'verbose_name': 'Информация о медицине',
                'verbose_name_plural': 'Медицина',
            },
        ),
    ]
