# Generated by Django 5.0.2 on 2024-06-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gobmp',
            name='additinaly',
            field=models.TextField(blank=True, verbose_name='Для получения путевки необходимо'),
        ),
        migrations.AddField(
            model_name='gobmp',
            name='additinaly_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Для получения путевки необходимо'),
        ),
        migrations.AddField(
            model_name='gobmp',
            name='additinaly_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Для получения путевки необходимо'),
        ),
        migrations.AddField(
            model_name='gobmp',
            name='adult',
            field=models.TextField(blank=True, verbose_name='Взрослые'),
        ),
        migrations.AddField(
            model_name='gobmp',
            name='adult_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Взрослые'),
        ),
        migrations.AddField(
            model_name='gobmp',
            name='adult_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Взрослые'),
        ),
        migrations.AddField(
            model_name='gobmp',
            name='children',
            field=models.TextField(blank=True, verbose_name='Дети'),
        ),
        migrations.AddField(
            model_name='gobmp',
            name='children_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Дети'),
        ),
        migrations.AddField(
            model_name='gobmp',
            name='children_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Дети'),
        ),
    ]
