# Generated by Django 5.0.2 on 2024-07-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobmp', '0005_rename_additinaly_kz_gobmp_additinaly_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gobmp',
            name='additinaly',
            field=models.TextField(verbose_name='Для получения путевки необходимо'),
        ),
        migrations.AlterField(
            model_name='gobmp',
            name='additinaly_en',
            field=models.TextField(null=True, verbose_name='Для получения путевки необходимо'),
        ),
        migrations.AlterField(
            model_name='gobmp',
            name='additinaly_kk',
            field=models.TextField(null=True, verbose_name='Для получения путевки необходимо'),
        ),
        migrations.AlterField(
            model_name='gobmp',
            name='additinaly_ru',
            field=models.TextField(null=True, verbose_name='Для получения путевки необходимо'),
        ),
    ]
