# Generated by Django 5.0.2 on 2024-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_page', '0008_rename_info_kz_pacientinfo_info_kk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientinfo',
            options={'verbose_name_plural': 'Правила'},
        ),
    ]
