# Generated by Django 5.0.2 on 2024-05-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_page', '0009_alter_pacientinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientinfo',
            options={'verbose_name': 'Правило', 'verbose_name_plural': 'Правила'},
        ),
    ]
