# Generated by Django 5.0.2 on 2024-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_page', '0012_alter_pacientinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientinfo',
            name='info_en',
            field=models.TextField(null=True, verbose_name='Information'),
        ),
        migrations.AddField(
            model_name='pacientinfo',
            name='title_en',
            field=models.CharField(null=True, verbose_name='Title'),
        ),
    ]
