# Generated by Django 5.0.2 on 2024-06-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_page', '0015_rename_info_kz_pacientinfo_info_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientinfo',
            name='info',
            field=models.TextField(verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='pacientinfo',
            name='info_en',
            field=models.TextField(null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='pacientinfo',
            name='info_kk',
            field=models.TextField(null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='pacientinfo',
            name='info_ru',
            field=models.TextField(null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='pacientinfo',
            name='title',
            field=models.CharField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='pacientinfo',
            name='title_en',
            field=models.CharField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='pacientinfo',
            name='title_kk',
            field=models.CharField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='pacientinfo',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Заголовок'),
        ),
    ]
