# Generated by Django 5.0.2 on 2024-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workersInfo', '0004_rename_post_kz_workersinfo_post_kk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workersinfo',
            options={'verbose_name_plural': 'О сотрудниках'},
        ),
    ]
