# Generated by Django 5.0.2 on 2024-05-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workersInfo', '0006_alter_workersinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workersinfo',
            options={},
        ),
    ]
