# Generated by Django 5.0.2 on 2024-05-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workersInfo', '0007_alter_workersinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workersinfo',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
