# Generated by Django 5.0.2 on 2024-06-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workersInfo', '0009_workersinfo_post_en_workersinfo_sertificates_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workersinfo',
            old_name='post_kk',
            new_name='post_kz',
        ),
        migrations.RenameField(
            model_name='workersinfo',
            old_name='sertificates_kk',
            new_name='sertificates_kz',
        ),
    ]
