# Generated by Django 5.0.2 on 2024-05-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0004_alter_index_page_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index_page',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информации'},
        ),
    ]
