# Generated by Django 5.0.2 on 2024-06-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0005_alter_index_page_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='openInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Заголовок')),
                ('file', models.FileField(upload_to='docs/', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Приказ о прозрачности',
            },
        ),
    ]
