# Generated by Django 5.0.2 on 2024-06-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0006_openinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinfo',
            name='file_kk',
            field=models.FileField(null=True, upload_to='docs/', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='openinfo',
            name='file_ru',
            field=models.FileField(null=True, upload_to='docs/', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='openinfo',
            name='title_kk',
            field=models.CharField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='openinfo',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Заголовок'),
        ),
    ]
