# Generated by Django 5.0.2 on 2024-06-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0007_openinfo_file_kk_openinfo_file_ru_openinfo_title_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinfo',
            name='file_kk',
        ),
        migrations.RemoveField(
            model_name='openinfo',
            name='file_ru',
        ),
    ]
