# Generated by Django 5.0.2 on 2024-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0008_remove_openinfo_file_kk_remove_openinfo_file_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_page',
            name='bannerContent_en',
            field=models.TextField(null=True, verbose_name='Текста на баннере'),
        ),
        migrations.AddField(
            model_name='index_page',
            name='ceo_appeal_en',
            field=models.TextField(null=True, verbose_name='Обращение руководителя'),
        ),
        migrations.AddField(
            model_name='openinfo',
            name='title_en',
            field=models.CharField(null=True, verbose_name='Заголовок'),
        ),
    ]
