# Generated by Django 5.0.2 on 2024-06-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0010_rename_bannercontent_kk_index_page_bannercontent_kz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index_page',
            old_name='bannerContent_kz',
            new_name='bannerContent_kk',
        ),
        migrations.RenameField(
            model_name='index_page',
            old_name='ceo_appeal_kz',
            new_name='ceo_appeal_kk',
        ),
        migrations.RenameField(
            model_name='openinfo',
            old_name='title_kz',
            new_name='title_kk',
        ),
    ]
