# Generated by Django 5.0.2 on 2024-06-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0011_rename_bannercontent_kz_index_page_bannercontent_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_page',
            name='mission',
            field=models.TextField(default=22, verbose_name='Миссия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index_page',
            name='mission_en',
            field=models.TextField(null=True, verbose_name='Миссия'),
        ),
        migrations.AddField(
            model_name='index_page',
            name='mission_kk',
            field=models.TextField(null=True, verbose_name='Миссия'),
        ),
        migrations.AddField(
            model_name='index_page',
            name='mission_ru',
            field=models.TextField(null=True, verbose_name='Миссия'),
        ),
        migrations.AddField(
            model_name='index_page',
            name='view',
            field=models.TextField(default=22, verbose_name='Видение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index_page',
            name='view_en',
            field=models.TextField(null=True, verbose_name='Видение'),
        ),
        migrations.AddField(
            model_name='index_page',
            name='view_kk',
            field=models.TextField(null=True, verbose_name='Видение'),
        ),
        migrations.AddField(
            model_name='index_page',
            name='view_ru',
            field=models.TextField(null=True, verbose_name='Видение'),
        ),
    ]
