# Generated by Django 5.0.2 on 2024-06-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0012_index_page_mission_index_page_mission_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_page',
            name='bannerContent',
        ),
        migrations.RemoveField(
            model_name='index_page',
            name='bannerContent_en',
        ),
        migrations.RemoveField(
            model_name='index_page',
            name='bannerContent_kk',
        ),
        migrations.RemoveField(
            model_name='index_page',
            name='bannerContent_ru',
        ),
        migrations.RemoveField(
            model_name='index_page',
            name='ceo_appeal',
        ),
        migrations.RemoveField(
            model_name='index_page',
            name='ceo_appeal_en',
        ),
        migrations.RemoveField(
            model_name='index_page',
            name='ceo_appeal_kk',
        ),
        migrations.RemoveField(
            model_name='index_page',
            name='ceo_appeal_ru',
        ),
    ]
