# Generated by Django 5.0.2 on 2024-04-26 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mediagallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название фотографии')),
                ('file', models.FileField(upload_to='mediagallery/', verbose_name='Файл')),
                ('date', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
