# Generated by Django 5.0.2 on 2024-04-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediagallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediagallery',
            name='name_kk',
            field=models.CharField(null=True, verbose_name='Название фотографии'),
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='name_ru',
            field=models.CharField(null=True, verbose_name='Название фотографии'),
        ),
    ]
