# Generated by Django 5.0.2 on 2024-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediagallery', '0002_mediagallery_name_kk_mediagallery_name_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediagallery',
            options={'verbose_name_plural': 'Фотографии'},
        ),
    ]
