# Generated by Django 5.0.2 on 2024-05-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediagallery', '0003_alter_mediagallery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediagallery',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
