# Generated by Django 5.0.2 on 2024-05-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediagallery', '0004_alter_mediagallery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediagallery',
            options={},
        ),
    ]
