# Generated by Django 5.0.2 on 2024-05-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_legends', '0005_alter_history_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История или легенда', 'verbose_name_plural': 'Истории и легенды'},
        ),
    ]
