# Generated by Django 5.0.2 on 2024-05-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_legends', '0009_history_poem_alter_history_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История НИИ', 'verbose_name_plural': 'История НИИ'},
        ),
    ]
