# Generated by Django 5.0.2 on 2024-06-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_legends', '0011_history_info_en_history_title_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='info_kk',
            new_name='info_kz',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='title_kk',
            new_name='title_kz',
        ),
    ]
