# Generated by Django 5.0.2 on 2024-05-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_pages', '0004_rename_info_kz_contacts_info_kk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Контакты НИИ'},
        ),
        migrations.AlterModelOptions(
            name='managers',
            options={'verbose_name_plural': 'Руководители'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='info',
            field=models.TextField(verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='info_kk',
            field=models.TextField(null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='info_ru',
            field=models.TextField(null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title',
            field=models.CharField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title_kk',
            field=models.CharField(null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='name',
            field=models.CharField(max_length=128, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='name_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='phone',
            field=models.CharField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='post',
            field=models.TextField(verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='post_kk',
            field=models.TextField(null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='post_ru',
            field=models.TextField(null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='reception',
            field=models.TextField(default='none', verbose_name='День и время приема'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='reception_kk',
            field=models.TextField(default='none', null=True, verbose_name='День и время приема'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='reception_ru',
            field=models.TextField(default='none', null=True, verbose_name='День и время приема'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='show',
            field=models.BooleanField(verbose_name='Отображать в 2 таблицах?'),
        ),
    ]
