# Generated by Django 5.0.2 on 2024-05-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_pages', '0006_alter_contacts_options_alter_managers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='managers',
            options={},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='info',
            field=models.TextField(verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='info_kk',
            field=models.TextField(null=True, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='info_ru',
            field=models.TextField(null=True, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title',
            field=models.CharField(verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title_kk',
            field=models.CharField(null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='name_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='phone',
            field=models.CharField(verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='post',
            field=models.TextField(verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='post_kk',
            field=models.TextField(null=True, verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='post_ru',
            field=models.TextField(null=True, verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='reception',
            field=models.TextField(default='none', verbose_name='Day and time of reception'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='reception_kk',
            field=models.TextField(default='none', null=True, verbose_name='Day and time of reception'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='reception_ru',
            field=models.TextField(default='none', null=True, verbose_name='Day and time of reception'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='show',
            field=models.BooleanField(verbose_name='Show this person in second table?'),
        ),
    ]
