# Generated by Django 5.0.2 on 2024-06-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_pages', '0008_alter_contacts_options_alter_managers_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAccessFaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='ФИО')),
                ('post', models.TextField(verbose_name='Должность')),
                ('phone', models.CharField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Уполномоченное лицо',
                'verbose_name_plural': 'Уполномоченые лица по вопросам доступа информации',
            },
        ),
    ]
