# Generated by Django 5.0.2 on 2024-06-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_pages', '0009_infoaccessfaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoaccessfaces',
            name='name_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='infoaccessfaces',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='infoaccessfaces',
            name='post_kk',
            field=models.TextField(null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='infoaccessfaces',
            name='post_ru',
            field=models.TextField(null=True, verbose_name='Должность'),
        ),
    ]
