# Generated by Django 5.0.2 on 2024-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_pages', '0010_infoaccessfaces_name_kk_infoaccessfaces_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='info_en',
            field=models.TextField(null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_en',
            field=models.CharField(null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='infoaccessfaces',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='infoaccessfaces',
            name='post_en',
            field=models.TextField(null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='managers',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='managers',
            name='post_en',
            field=models.TextField(null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='managers',
            name='reception_en',
            field=models.TextField(default='none', null=True, verbose_name='День и время приема'),
        ),
    ]
