# Generated by Django 5.0.2 on 2024-06-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_pages', '0014_alter_managers_reception_alter_managers_reception_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='reception',
            field=models.TextField(default='none', verbose_name='День и время приема'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='reception_en',
            field=models.TextField(default='none', null=True, verbose_name='День и время приема'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='reception_kk',
            field=models.TextField(default='none', null=True, verbose_name='День и время приема'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='reception_ru',
            field=models.TextField(default='none', null=True, verbose_name='День и время приема'),
        ),
    ]
