# Generated by Django 5.0.2 on 2024-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceoblog', '0002_postceo_content_kk_postceo_content_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postceo',
            options={'verbose_name_plural': 'Посты руководителя'},
        ),
    ]
