# Generated by Django 5.0.2 on 2024-05-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceoblog', '0003_alter_postceo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postceo',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты руководителя'},
        ),
    ]
