# Generated by Django 5.0.2 on 2024-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceoblog', '0006_alter_postceo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='postceo',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='postceo',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
    ]
