# Generated by Django 5.0.2 on 2024-06-25 21:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceoblog', '0009_rename_content_kz_postceo_content_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='file',
            field=models.FileField(upload_to='images/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceoblog.postceo', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='type',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='postceo',
            name='content',
            field=models.TextField(verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='postceo',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='postceo',
            name='content_kk',
            field=models.TextField(null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='postceo',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='postceo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='postceo',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='postceo',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='postceo',
            name='title_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='postceo',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок'),
        ),
    ]
