# Generated by Django 5.0.2 on 2024-05-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0009_rename_additionally_kz_ceodatas_additionally_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceodatas',
            name='additionally',
        ),
        migrations.RemoveField(
            model_name='ceodatas',
            name='additionally_kk',
        ),
        migrations.RemoveField(
            model_name='ceodatas',
            name='additionally_ru',
        ),
    ]
