# Generated by Django 5.0.2 on 2024-05-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0010_remove_ceodatas_additionally_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceodatas',
            name='work_ex',
        ),
        migrations.RemoveField(
            model_name='ceodatas',
            name='work_ex_kk',
        ),
        migrations.RemoveField(
            model_name='ceodatas',
            name='work_ex_ru',
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='positions',
            field=models.TextField(default=17, verbose_name='Должности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='positions_kk',
            field=models.TextField(null=True, verbose_name='Должности'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='positions_ru',
            field=models.TextField(null=True, verbose_name='Должности'),
        ),
    ]
