# Generated by Django 5.0.2 on 2024-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0012_ceodatas_education_ceodatas_education_kk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceodatas',
            options={'verbose_name_plural': 'Информация о руководителе'},
        ),
    ]
