# Generated by Django 5.0.2 on 2024-05-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0016_alter_ceodatas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceodatas',
            name='work',
            field=models.TextField(blank=True, verbose_name='Трудовая деятельность'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='work_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Трудовая деятельность'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='work_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Трудовая деятельность'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='awards',
            field=models.TextField(blank=True, verbose_name='Награды'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='awards_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Награды'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='awards_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Награды'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='positions',
            field=models.TextField(blank=True, verbose_name='Должности'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='positions_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Должности'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='positions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Должности'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='publications',
            field=models.TextField(blank=True, verbose_name='Публикации'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='publications_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Публикации'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='publications_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Публикации'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='scientific',
            field=models.TextField(blank=True, verbose_name='Научная степень'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='scientific_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Научная степень'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='scientific_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Научная степень'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='sertificates',
            field=models.TextField(blank=True, verbose_name='Сертификаты'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='sertificates_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Сертификаты'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='sertificates_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Сертификаты'),
        ),
    ]
