# Generated by Django 5.0.2 on 2024-06-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0017_ceodatas_work_ceodatas_work_kk_ceodatas_work_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceodatas',
            name='post',
            field=models.CharField(blank=True, verbose_name='Должность'),
        ),
    ]
