# Generated by Django 5.0.2 on 2024-06-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0018_ceodatas_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceodatas',
            name='post_kk',
            field=models.CharField(blank=True, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='post_ru',
            field=models.CharField(blank=True, null=True, verbose_name='Должность'),
        ),
    ]
