# Generated by Django 5.0.2 on 2024-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0019_ceodatas_post_kk_ceodatas_post_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceodatas',
            name='awards_en',
            field=models.TextField(blank=True, null=True, verbose_name='Награды'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='dateOfBirth_en',
            field=models.CharField(null=True, verbose_name='Дата рождания'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='education_en',
            field=models.TextField(null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='name_en',
            field=models.CharField(null=True, verbose_name='Имя руководителя'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='positions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Должности'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='post_en',
            field=models.CharField(blank=True, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='publications_en',
            field=models.TextField(blank=True, null=True, verbose_name='Публикации'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='scientific_en',
            field=models.TextField(blank=True, null=True, verbose_name='Научная степень'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='sertificates_en',
            field=models.TextField(blank=True, null=True, verbose_name='Сертификаты'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='work_en',
            field=models.TextField(blank=True, null=True, verbose_name='Трудовая деятельность'),
        ),
    ]
