# Generated by Django 5.0.2 on 2024-06-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0021_rename_awards_kk_ceodatas_awards_kz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ceodatas',
            old_name='awards_kz',
            new_name='awards_kk',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='dateOfBirth_kz',
            new_name='dateOfBirth_kk',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='education_kz',
            new_name='education_kk',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='name_kz',
            new_name='name_kk',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='positions_kz',
            new_name='positions_kk',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='post_kz',
            new_name='post_kk',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='publications_kz',
            new_name='publications_kk',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='scientific_kz',
            new_name='scientific_kk',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='sertificates_kz',
            new_name='sertificates_kk',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='work_kz',
            new_name='work_kk',
        ),
    ]
